### PR TITLE
Fixes the undefined offset notice when no project is assigned to a task

### PR DESCRIPTION
**Pull request by ajitdev**
Steps to reproduce:
1. Create an task in any workspace in Asana.
2. Do not associate this task to any project.
3. Open asana time tracker
4. Select the workspace under which you created the task.

Expected result : User should be notified "NO PROJECT" under the project.

Actual result : Gets an error : 
Notice: Undefined offset: 0 in /var/www/apps/asana/AsanaApi.php on line 66

This PR would fix this.

### CODE REVIEW

**Comment by MathiasTim** [comment]
Looks great, although all my Tasks, which are subtasks, now tell me they're in "NO PROJECT". Maybe a fix there, then I'll merge it. 

Thanks anyway!

**Comment by ajitdev** [comment]
Thank you for the quick review. I was able to reproduce the "NO PROJECT" on the subtasks. I am working on it will commit the code when I'm able to fix it.

**Comment by ajitdev** [comment]
@MathiasTim I have added a check to see if a task has a parent task (i.e. it is a subtask). If it is then the project will contain
SUB TASK : {name of the task}

**Comment by MathiasTim** [comment]
looks great, send a new Pull Request and I'll merge it.

edit: saw you already done it, thanks!

**Pull request merged**
